vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       posts:
           uri_prefix: /img/posts
           upload_destination: '%kernel.project_dir%/public/img/posts'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
